"""Per-object settings that rebuild the dirt strip live when you change them.

Everything mechanical here belongs to Ambient Occlusion and is imported from
it: the serialisation of the source edges, the strip bevel, and the rebuild
itself, which takes the per-object group to read as an argument precisely so
this tool can hand it its own. See fake_ao/object_settings.py for why the
rebuild uses no `bpy.ops` at all.

The only thing this module owns is the group: `Object.seto_edge_dirt_data`,
separate from the AO one so a wall can carry an AO strip and a dirt strip at
once without the panel showing one strip's settings on the other.
"""

import bpy

from . import properties
from ..shared import manual_offset
from ..fake_ao.object_settings import (  # noqa: F401  (re-exported for this package)
    UV_SIZE,
    apply_strip_bevel,
    is_rebuilding,
    parse_edge_keys,
    rebuild as _ao_rebuild,
    serialise_edge_keys,
    serialise_segments,
    suppress_rebuild,
)


def rebuild(obj):
    """Regenerate `obj`'s mesh from its stored source, edges and settings."""
    return _ao_rebuild(obj, obj.seto_edge_dirt_data)


def _on_setting_changed(self, context):
    """Property update callback - `self` is the per-object PropertyGroup."""
    obj = getattr(self, "id_data", None)
    if obj is None or not isinstance(obj, bpy.types.Object):
        return
    if is_rebuilding() or not self.is_edge_dirt:
        return
    # The source's round is a modifier, not a rebuild, so it is kept in step
    # here rather than inside rebuild() - and it happens even with Live Update
    # off, because a modifier is not the strip's geometry.
    from ..fake_ao import source_bevel
    source_bevel.sync(self.source_object, leader=obj, tool=source_bevel.EDGE_DIRT)
    if not self.live_update:
        return
    self.status = rebuild(obj) or ""


def _object_annotations():
    """Bookkeeping properties, plus the tool's settings wired to rebuild the
    object as soon as they change."""
    annotations = {
        "is_edge_dirt": bpy.props.BoolProperty(
            name="Is Edge Dirt",
            description="Marks an object as generated by this tool, so the panel knows to show its settings",
            default=False,
        ),
        "source_object": bpy.props.PointerProperty(
            name="Source",
            description="The mesh this strip was generated from. Rebuilding reads its edges again",
            type=bpy.types.Object,
        ),
        "edge_keys": bpy.props.StringProperty(
            name="Edge Keys",
            description="Source-mesh vertex index pairs of the edges this strip was built along",
            default="",
        ),
        "frozen_segments": bpy.props.StringProperty(
            name="Frozen Segments",
            description=(
                "The corner geometry this strip was built from, kept verbatim for the case "
                "where the source edge was beveled away and its indices no longer mean anything"
            ),
            default="",
        ),
        "live_update": bpy.props.BoolProperty(
            name="Live Update",
            description=(
                "Rebuild the strip immediately whenever a setting below changes. Turn off on very "
                "heavy selections and use Rebuild Now instead"
            ),
            default=True,
        ),
        "status": bpy.props.StringProperty(
            name="Status",
            description="Why the last rebuild could not run, if it could not",
            default="",
        ),
    }
    annotations.update(manual_offset.annotations())
    annotations.update(properties.settings_annotations(update=_on_setting_changed))
    return annotations


class SETO_PG_edge_dirt_object(bpy.types.PropertyGroup):
    __annotations__ = _object_annotations()


class SETO_OT_edge_dirt_rebuild(bpy.types.Operator):
    """Regenerate this Edge Dirt strip from its stored source edges and settings"""
    bl_idname = "seto.edge_dirt_rebuild"
    bl_label = "Rebuild Now"
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        obj = context.active_object
        return obj is not None and obj.type == 'MESH' and obj.seto_edge_dirt_data.is_edge_dirt

    def execute(self, context):
        obj = context.active_object
        message = rebuild(obj)
        obj.seto_edge_dirt_data.status = message or ""
        if message:
            self.report({'WARNING'}, message)
            return {'CANCELLED'}
        self.report({'INFO'}, f"Rebuilt '{obj.name}' ({len(obj.data.polygons)} quad(s)).")
        return {'FINISHED'}


_classes = (
    SETO_PG_edge_dirt_object,
    SETO_OT_edge_dirt_rebuild,
)


def register():
    for cls in _classes:
        bpy.utils.register_class(cls)
    bpy.types.Object.seto_edge_dirt_data = bpy.props.PointerProperty(type=SETO_PG_edge_dirt_object)


def unregister():
    del bpy.types.Object.seto_edge_dirt_data
    for cls in reversed(_classes):
        bpy.utils.unregister_class(cls)
